### ISSUE TITLE
Act_6-Anteproyecto-equipo5

### ISSUE THREAD

**Issue by Daisy-GonzalezLita12** [SistemasTecTlaxiaco/actividad-6-anteproyecto-equipo-5#2]
Reporte de anteproyecto de Paris Chiquito y su pan
integrantes de equipo DAISY GONZÁLEZ LITA,  ANA KIMBERLY HERNÁNDEZ PÉREZ, ARIADNA MONSERRAT LÓPEZ APARICIO Y MARIBEL SANTIAGO BAUTISTA.
grupo:1bs
[anteproyecto_1.pdf](https://github.com/SistemasTecTlaxiaco/actividad-6-anteproyecto-equipo-5/files/9676099/anteproyecto_1.pdf)

**Comment by ErikCuevas03** [comment]
15
En la portada, en la parte de lsos nombres se encuentran desordenado y dificulta la visibilidad de los integrantes.
Asimismo  hay faltas de redacción en la parte del efecto  y por el último en el objetivo falto mencionar el lugar en el cual esta dirigido el anteproyecto

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
